### ISSUE TITLE
param.defaultvalue is not a string

### ISSUE THREAD

**Issue by calbertts** [erinspice/confluence-jsdoc-template#7]
My docs work with any other templates, but this one.
JSDocs version: `JSDoc 3.6.4`
```
undefined:92
 param.defaultvalue.replace(/\n/g, ' ')
                    ^

TypeError: param.defaultvalue.replace is not a function
    at eval (eval at template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1596:16), <anonymous>:92:21)
    at Array.forEach (<anonymous>)
    at Template.eval (eval at template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1596:16), <anonymous>:62:13)
    at Template.template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1603:21)
    at Template.partial (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/lib/jsdoc/template.js:55:33)
    at eval (eval at template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1596:16), <anonymous>:104:14)
    at Array.forEach (<anonymous>)
    at Template.eval (eval at template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1596:16), <anonymous>:60:13)
    at Template.template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1603:21)
    at Template.partial (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/lib/jsdoc/template.js:55:33)
    at Template.eval (eval at template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1596:16), <anonymous>:98:14)
    at Template.template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1603:21)
    at Template.partial (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/lib/jsdoc/template.js:55:33)
    at eval (eval at template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1596:16), <anonymous>:139:14)
    at Array.forEach (<anonymous>)
    at eval (eval at template (/Users/calbertts/.nvm/versions/node/v11.15.0/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1596:16), <anonymous>:137:10)
```

**Comment by mathias22osterhagen22** [comment]
Same but with not a function: 
![image](https://user-images.githubusercontent.com/60438474/101797782-b1955e00-3b0a-11eb-83db-b226daf41e8c.png)
